namespace:
  name: ''
commonLabels:
  app.kubernetes.io/part-of: production-ai-platform
networkPolicy:
  enabled: true
  ingressCidrs:
  - 10.0.0.0/8
metrics:
  enabled: true
  namespaceSelector:
    kubernetes.io/metadata.name: observability
  podSelector:
    app.kubernetes.io/name: prometheus
api:
  service:
    type: ClusterIP
    port: 8000
    annotations: {}
web:
  service:
    type: ClusterIP
    port: 3000
appReleaseName: ai-platform
nameOverride: ai-platform
fullnameOverride: ai-platform
