FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache su-exec

RUN addgroup -S nodejs \
    && adduser -S nextjs -G nodejs -u 10001

COPY package*.json ./
RUN npm ci

COPY . .
COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.dev.sh

RUN chown -R nextjs:nodejs /app \
    && chmod +x /usr/local/bin/docker-entrypoint.dev.sh

USER nextjs

ENTRYPOINT ["docker-entrypoint.dev.sh"]

EXPOSE 3000

CMD ["npm", "run", "dev"]
