FROM node:20-alpine

WORKDIR /app

RUN addgroup -S nodejs \
    && adduser -S nextjs -G nodejs -u 10001

COPY package*.json ./
RUN npm ci

COPY . .

RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["npm", "run", "dev"]
