namespace:
  create: true
  name: ai-platform-prod

api:
  replicaCount: 3
  image:
    repository: replace-with-prod-ecr/production-ai-platform/api
    tag: prod
  config:
    environment: prod
    corsOrigins: https://ai-platform.example.com
    tracingEnabled: "false"
    otelServiceName: production-ai-platform-api-prod
    otelTracesExporter: otlp
    otelExporterOtlpEndpoint: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 65

web:
  replicaCount: 3
  image:
    repository: replace-with-prod-ecr/production-ai-platform/web
    tag: prod
  config:
    apiBaseUrl: https://api.ai-platform.example.com
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 65

ingress:
  webHost: ai-platform.example.com
  apiHost: api.ai-platform.example.com
