namespace:
  create: true
  name: ai-platform-dev
externalSecrets:
  runtime:
    remoteKey: production-ai-platform-dev/runtime
api:
  replicaCount: 1
  image:
    repository: replace-with-dev-ecr/production-ai-platform/api
    tag: dev
  config:
    environment: dev
  autoscaling:
    enabled: false
web:
  replicaCount: 1
  image:
    repository: replace-with-dev-ecr/production-ai-platform/web
    tag: dev
  config:
    origin: https://dev.ai-platform.example.com
  autoscaling:
    enabled: false
ingress:
  webHost: dev.ai-platform.example.com
  apiHost: api.dev.ai-platform.example.com
migration:
  image:
    repository: replace-with-dev-ecr/production-ai-platform/migration
    tag: dev
