namespace:
  name: ai-platform-prod
api:
  replicaCount: 3
  image:
    repository: replace-with-prod-ecr/production-ai-platform/api
    tag: prod
  config:
    environment: prod
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 65
    scaleUpStabilizationWindowSeconds: 30
    scaleDownStabilizationWindowSeconds: 300
  podDisruptionBudget:
    minAvailable: 2
web:
  replicaCount: 3
  image:
    repository: replace-with-prod-ecr/production-ai-platform/web
    tag: prod
  config:
    origin: https://ai-platform.example.com
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 65
    scaleUpStabilizationWindowSeconds: 30
    scaleDownStabilizationWindowSeconds: 300
  podDisruptionBudget:
    minAvailable: 2
ingress:
  webHost: ai-platform.example.com
  apiHost: api.ai-platform.example.com
