apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-platform
  namespace: argocd
spec:
  description: Production AI Platform GitOps applications
  sourceRepos:
    - https://github.com/christiankfoury/llmops-platform.git
  destinations:
    - namespace: ai-platform-dev
      server: https://kubernetes.default.svc
    - namespace: ai-platform-staging
      server: https://kubernetes.default.svc
    - namespace: ai-platform-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: external-secrets.io
      kind: ClusterSecretStore
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: external-secrets.io
      kind: ExternalSecret
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
  orphanedResources:
    warn: true
