apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-platform-runtime
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: ai-platform-runtime
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: production-ai-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ai-platform-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ai-platform-runtime-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-password
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: database-password
  - secretKey: database-username
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: database-username
  - secretKey: jdbc-database-url
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: jdbc-database-url
  - secretKey: redis-host
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: redis-host
  - secretKey: redis-password
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: redis-password
  - secretKey: redis-port
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: redis-port
  - secretKey: redis-username
    remoteRef:
      key: production-ai-platform-dev/runtime
      property: redis-username
