apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceaccount-api.yaml
- serviceaccount-web.yaml
- configmap-api.yaml
- configmap-web.yaml
- deployment-api.yaml
- deployment-web.yaml
- hpa-api.yaml
- hpa-web.yaml
- pdb-api.yaml
- pdb-web.yaml
- service-api.yaml
- service-web.yaml
- ingress.yaml
- networkpolicy.yaml
- service-metrics.yaml
images:
- name: production-ai-platform-api
  newName: replace-with-ecr/production-ai-platform/api
  newTag: latest
- name: production-ai-platform-web
  newName: replace-with-ecr/production-ai-platform/web
  newTag: latest
