{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.externalSecrets.secretStore.kind }}
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "ai-platform.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.externalSecrets.secretStore.service }}
      region: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.controllerServiceAccountName }}
            namespace: {{ .Values.externalSecrets.secretStore.controllerServiceAccountNamespace }}
{{- end }}
